Práctica 2. Métricas de evaluación

Realizar al menos 5 entrenamientos y luego informa los promedios de accuracy, precision, recall y F1-score, tanto para la clase 0 como para la clase 1.

In [1]:
from keras.datasets import mnist
import numpy as np

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Se obtiene una muestra con igual número de: cincos vs no cincos
# para el conjunto de entrenamiento y el de test
idx_y_train_5 = np.where(y_train == 5)[0]
idx_y_train_n5 = np.where(y_train != 5)[0]
idx_y_train_n5 = np.random.choice(idx_y_train_n5, idx_y_train_5.shape[0], replace=False)

idx_y_train = np.concatenate([idx_y_train_5, idx_y_train_n5])
np.random.shuffle(idx_y_train)

x_train = x_train[idx_y_train]
y_train = y_train[idx_y_train]
print(x_train.shape)

idx_y_test_5 = np.where(y_test == 5)[0]
idx_y_test_n5 = np.where(y_test != 5)[0]
idx_y_test_n5 = np.random.choice(idx_y_test_n5, idx_y_test_5.shape[0], replace=False)

idx_y_test = np.concatenate([idx_y_test_5, idx_y_test_n5])
np.random.shuffle(idx_y_test)

x_test = x_test[idx_y_test]
y_test = y_test[idx_y_test]
print(x_test.shape)

y_train_binary = (y_train == 5).astype(int)
y_test_binary = (y_test == 5).astype(int)

11490434/11490434 [==============================] - 0s 0us/step
(10842, 28, 28)
(1784, 28, 28)


In [2]:
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.metrics import F1Score

# Se crea un modelo secuencial con dos capas:
#Capa de aplanamiento (Flatten) para convertir las imágenes 2D en un vector 1D
#Capa densa (Dense) con una sola unidad.
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(1)
])

print(model.summary()) #Imprimir un resumen del modelo

model.compile(loss='binary_crossentropy', metrics=['accuracy']) #Compilar el modelo

#Entrenar el modelo en el conjunto de datos de entrenamiento
model.fit(x_train, y_train_binary, epochs=4, batch_size=2000, validation_split=0.9)
#Durante 4 épocas con lotes de tamaño 2000 y utiliza el 90% de los datos para validación.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 1)                 785       
                                                                 
Total params: 785 (3.07 KB)
Trainable params: 785 (3.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/4
1/1 [==============================] - 2s 2s/step - loss: 7.1374 - accuracy: 0.5341 - val_loss: 7.4297 - val_accuracy: 0.5166
Epoch 2/4
1/1 [==============================] - 0s 106ms/step - loss: 6.9779 - accuracy: 0.5461 - val_loss: 7.4476 - val_accuracy: 0.5156
Epoch 3/4
1/1 [==============================] - 0s 81ms/step - loss: 7.0107 - accuracy: 0.5443 - val_loss: 7.4757 - val_accuracy: 0.5148
Epoc

In [3]:
from sklearn.metrics import confusion_matrix, \
precision_score, recall_score,f1_score

#Utilizar el modelo entrenado para hacer predicciones sobre el conjunto de prueba.
y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]

#Matriz de confusión para analizar el rendimiento del modelo de clasificación
conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

# Métricas de evaluación de modelos de clasificación para analizar el rendimiento del modelo en el conjunto de prueba.

#Precision, Recall(sensibilidad) y F1-score para la clase 1:
precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)

# Precision, Recall(sensibilidad) y F1-score para la clase 0:
precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

56/56 [==============================] - 0s 2ms/step
Matriz de confusión:
[[804  88]
 [758 134]]
Precision_1: 0.6036036036036037
Recall_1: 0.15022421524663676
F1-score_1: 0.24057450628366248
Precision_0: 0.5147247119078106
Recall_0: 0.9013452914798207
F1-score_0: 0.6552567237163814


2. epochs = 20, batchsize = 2000, validation_split = 0.9

In [4]:
#Entrenar el modelo en el conjunto de datos de entrenamiento
model.fit(x_train, y_train_binary, epochs=20, batch_size=2000, validation_split=0.9)
#Durante 20 épocas con lotes de tamaño 2000 y utiliza el 90% de los datos para validación

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]

conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

#Precision, Recall(sensibilidad) y F1-score para la clase 1:
precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)

# Precision, Recall(sensibilidad) y F1-score para la clase 0:
precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

Epoch 1/20
1/1 [==============================] - 0s 118ms/step - loss: 6.8807 - accuracy: 0.5526 - val_loss: 7.2444 - val_accuracy: 0.5294
Epoch 2/20
1/1 [==============================] - 0s 54ms/step - loss: 6.8505 - accuracy: 0.5554 - val_loss: 7.2009 - val_accuracy: 0.5318
Epoch 3/20
1/1 [==============================] - 0s 56ms/step - loss: 6.7944 - accuracy: 0.5581 - val_loss: 7.0911 - val_accuracy: 0.5386
Epoch 4/20
1/1 [==============================] - 0s 96ms/step - loss: 6.5820 - accuracy: 0.5720 - val_loss: 6.8871 - val_accuracy: 0.5509
Epoch 5/20
1/1 [==============================] - 0s 99ms/step - loss: 6.3479 - accuracy: 0.5858 - val_loss: 6.7679 - val_accuracy: 0.5581
Epoch 6/20
1/1 [==============================] - 0s 56ms/step - loss: 6.4660 - accuracy: 0.5784 - val_loss: 6.7302 - val_accuracy: 0.5606
Epoch 7/20
1/1 [==============================] - 0s 68ms/step - loss: 6.3176 - accuracy: 0.5876 - val_loss: 6.6805 - val_accuracy: 0.5644
Epoch 8/20
1/1 [==========

3. epochs = 4, batchsize = 2, validation_split = 0.9

In [6]:
#Entrenar el modelo en el conjunto de datos de entrenamiento
model.fit(x_train, y_train_binary, epochs=4, batch_size=2, validation_split=0.9)
#Durante 4 épocas con lotes de tamaño 2 y utiliza el 90% de los datos para validación

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]

conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

#Precision, Recall(sensibilidad) y F1-score para la clase 1:
precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)

# Precision, Recall(sensibilidad) y F1-score para la clase 0:
precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

Epoch 1/4
542/542 [==============================] - 12s 22ms/step - loss: 5.3750 - accuracy: 0.6504 - val_loss: 6.0062 - val_accuracy: 0.6072
Epoch 2/4
542/542 [==============================] - 12s 21ms/step - loss: 5.3750 - accuracy: 0.6504 - val_loss: 6.0062 - val_accuracy: 0.6072
Epoch 3/4
542/542 [==============================] - 7s 12ms/step - loss: 5.3750 - accuracy: 0.6504 - val_loss: 6.0062 - val_accuracy: 0.6072
Epoch 4/4
56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[658 234]
 [477 415]]
Precision_1: 0.6394453004622496
Recall_1: 0.46524663677130046
F1-score_1: 0.5386112913692408
Precision_0: 0.5797356828193833
Recall_0: 0.7376681614349776
F1-score_0: 0.6492353231376419


4. epochs = 4, batchsize = 2000, validation_split = 0.01

In [7]:
#Entrenar el modelo en el conjunto de datos de entrenamiento
model.fit(x_train, y_train_binary, epochs=4, batch_size=2000, validation_split=0.01)
#Durante 4 épocas con lotes de tamaño 2000 y utiliza el 1% de los datos para validación

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]

conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

#Precision, Recall(sensibilidad) y F1-score para la clase 1:
precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)

# Precision, Recall(sensibilidad) y F1-score para la clase 0:
precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

Epoch 1/4
6/6 [==============================] - 0s 20ms/step - loss: 5.7699 - accuracy: 0.6215 - val_loss: 4.7807 - val_accuracy: 0.6881
Epoch 2/4
6/6 [==============================] - 0s 11ms/step - loss: 4.8258 - accuracy: 0.6842 - val_loss: 3.8013 - val_accuracy: 0.7523
Epoch 3/4
6/6 [==============================] - 0s 11ms/step - loss: 4.3743 - accuracy: 0.7134 - val_loss: 3.7933 - val_accuracy: 0.7431
Epoch 4/4
56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[552 340]
 [132 760]]
Precision_1: 0.6909090909090909
Recall_1: 0.852017937219731
F1-score_1: 0.7630522088353414
Precision_0: 0.8070175438596491
Recall_0: 0.6188340807174888
F1-score_0: 0.7005076142131981


5. Busca una configuración de estos hiperparámetros que optimice las métricas, tu notebook debe tener un entrenamiento con esta configuración.

In [25]:
#Entrenar el modelo en el conjunto de datos de entrenamiento
model.fit(x_train, y_train_binary, epochs=4, batch_size=130, validation_split=0.2)

y_pred = (model.predict(x_test) >= 0.5).astype(int)[:,0]

conf_matrix = confusion_matrix(y_test_binary, y_pred)
print("Matriz de confusión:")
print(conf_matrix)

#Precision, Recall(sensibilidad) y F1-score para la clase 1:
precision = precision_score(y_test_binary, y_pred)
print("Precision_1:", precision)
recall = recall_score(y_test_binary, y_pred)
print("Recall_1:", recall)
f1_s = f1_score(y_test_binary, y_pred)
print("F1-score_1:", f1_s)

# Precision, Recall(sensibilidad) y F1-score para la clase 0:
precision_0 = precision_score(y_test_binary, y_pred, pos_label=0)
print("Precision_0:", precision_0)
recall_0 = recall_score(y_test_binary, y_pred, pos_label=0)
print("Recall_0:", recall_0)
f1_s_0 = f1_score(y_test_binary, y_pred, pos_label=0)
print("F1-score_0:", f1_s_0)

Epoch 1/4
67/67 [==============================] - 1s 8ms/step - loss: 2.4770 - accuracy: 0.8367 - val_loss: 2.5290 - val_accuracy: 0.8340
Epoch 2/4
67/67 [==============================] - 0s 3ms/step - loss: 2.3886 - accuracy: 0.8434 - val_loss: 2.5355 - val_accuracy: 0.8331
Epoch 3/4
67/67 [==============================] - 0s 3ms/step - loss: 2.3239 - accuracy: 0.8471 - val_loss: 2.3591 - val_accuracy: 0.8456
Epoch 4/4
56/56 [==============================] - 0s 1ms/step
Matriz de confusión:
[[819  73]
 [211 681]]
Precision_1: 0.903183023872679
Recall_1: 0.7634529147982063
F1-score_1: 0.8274605103280681
Precision_0: 0.7951456310679612
Recall_0: 0.9181614349775785
F1-score_0: 0.8522372528616026
